accounts/urls.py
from django.urls import path

from accounts import views

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup')
]

shortener/urls.py
from django.urls import path

from shortener import views


app_name = 'shortener'

urlpatterns = [
    path('', views.index, name='index'),
    path('my-urls/', views.user_urls_list, name='user_urls_list'),
    path('<str:url_id>/', views.get_original_url, name='get_origin'),
]

shurl_api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from shurl_api import views

router = DefaultRouter()
router.register(r'urls', views.UrlViewSet)
router.register(r'users', views.UserViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

url_shorter/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api/', include('shurl_api.urls')),
    path('', include('shortener.urls')),
]

shortener/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from datetime import date


class Url(models.Model):
    created_by = models.ForeignKey(User, null=True, blank=True, related_name='urls', on_delete=models.CASCADE)
    url_id = models.SlugField(max_length=7, primary_key=True)
    url = models.URLField(max_length=250)
    short_link = models.URLField(null=True, blank=True)
    date_created = models.DateField(auto_now_add=True)
    days_to_expiry = models.IntegerField(default=90)

    def __str__(self):
        return self.url

    def save(self, *args, **kwargs):
        self.short_link = settings.SITE_URL + self.url_id
        super(Url, self).save(*args, **kwargs)

    def check_expiry_date(self):
        if (date.today() - self.date_created).days > self.days_to_expiry:
            super(Url, self).delete()
            return False
        return True

shurl_api/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.urls import reverse_lazy
from django.views import generic


class UserCreateForm(UserCreationForm):
    email = forms.EmailField(required=False)

    def __init__(self, *args, **kwargs):
        super(UserCreateForm, self).__init__(*args, **kwargs)
        self.fields.pop('email')

        # for fieldname in ['username', 'password1', 'password2']:
        #     self.fields[fieldname].help_text = None


class SignUp(generic.CreateView):
    form_class = UserCreateForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

shortener/views.py
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect, Http404
from django.conf import settings
from shortener.models import Url
from shortener.utils import get_short_code_for_url

from datetime import timedelta


def index(request):
    if request.method == "POST":
        url = request.POST.get('url', '')
        days = request.POST.get('days', '')

        try:
            days = int(days)
        except ValueError:
            days = 90

        url_id = get_short_code_for_url()
        if request.user.is_authenticated:
            url_object = Url.objects.create(url_id=url_id, url=url, days_to_expiry=days, created_by=request.user)
        else:
            url_object = Url.objects.create(url_id=url_id, url=url, days_to_expiry=days)
        expiry_date = url_object.date_created + timedelta(days=url_object.days_to_expiry)
        site_url = settings.SITE_URL

        return render(request, 'shortener/index.html', {'url_object': url_object, 'site_url': site_url, 'expiry_date': expiry_date})

    return render(request, 'shortener/index.html')


def get_original_url(request, url_id):
    url = get_object_or_404(Url, pk=url_id)

    if not url.check_expiry_date():
        return redirect('/')

    if any(url.url.strip().startswith(prt) for prt in ['https', 'http']):
        return HttpResponseRedirect(url.url.strip())
    else:
        if url.url.startswith('www.'):
            return HttpResponseRedirect('http://' + url.url.strip('www.'))
        return HttpResponseRedirect('http://' + url.url)


def user_urls_list(request):
    if request.user.is_authenticated:

        user_urls = [url.check_expiry_date() for url in Url.objects.filter(created_by=request.user)]
        user_urls = Url.objects.filter(created_by=request.user)

        site_url = settings.SITE_URL

        return render(request, 'shortener/user_urls.html', {'user_urls': user_urls, 'site_url': site_url})

    return redirect('shortener:index')

shurl_api/views.py
from rest_framework import viewsets
from rest_framework import permissions

from django.contrib.auth.models import User

from shurl_api.serializers import UserSerializer, UrlSerializer
from shurl_api.permissions import IsOwnerOrReadOnly
from shortener.models import Url
from shortener.utils import get_short_code_for_url


class UserViewSet(viewsets.ReadOnlyModelViewSet):

    queryset = User.objects.all()
    serializer_class = UserSerializer


class UrlViewSet(viewsets.ModelViewSet):

    queryset = Url.objects.all()
    serializer_class = UrlSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly,
                          IsOwnerOrReadOnly]

    def perform_create(self, serializer):
        serializer.save(created_by=self.request.user, url_id=get_short_code_for_url())

templates/shortener/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>{% block title %}Url shortening service {% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-secondary nbar">
      <a class="navbar-brand nbrand" href="{% url 'shortener:index' %}">shURL</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#"><span class="sr-only">(current)</span></a>
          </li>

        </ul>
          <ul class="navbar-nav">

            {% if request.user.is_authenticated %}
              <a class="nav-link" href="{% url 'shortener:user_urls_list' %}">My URLs <span class="sr-only">(current)</span></a>
              <a class="nav-link" href="{% url 'logout' %}">Log Out ({{ request.user.username }}) <span class="sr-only">(current)</span></a>
            {% else %}
              <a class="nav-link" href="{% url 'login' %}">Log In <span class="sr-only">(current)</span></a>
              <a class="nav-link" href="{% url 'signup' %}">Sign Up <span class="sr-only">(current)</span></a>
            {% endif %}

          </ul>
      </div>
    </nav>

{% block content %}

{% endblock %}


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

templates/shortener/index.html
{% extends 'shortener/base.html' %}
{% block content %}
<div class="container">
    <div class="row mt-5">
        <div class="col-sm-2"></div>
        <div class="col-sm-8">
            <div class="card text-center">
              <div class="card-header">
                Shorten your URL
              </div>
              <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                  <div class="form-group">
                    <label for="urlInput">Enter Url:</label>
                    <input type="text" class="form-control" id="urlInput" name="url" placeholder="Enter URL" autocomplete="new-password">
                  </div>
                  <div class="form-group">
                    <label for="daysToExpiration">Days to expiration (default 90) :</label>
                    <input type="text" class="form-control" id="daysToExpiration" name="days" placeholder="Number of days" autocomplete="new-password">
                  </div>
                  <button type="submit" class="btn btn-primary">Submit</button>
                </form>

                {% if url_object %}
                <div class="card mt-4">
                    <div class="card-header">
                        Results
                    </div>
                    <div class="card-body">
                        <p class="card-text">Great! Your URL is ready to use.
                            {% if request.user.is_authenticated %}
                                This URL is on your Urls page.
                            {% else %}
                                You are not logged in, so save this url somewhere before closing this page.
                            {% endif %}
                            URL will expire on {{ expiry_date }}.
                        </p>

                        <p class="card-text">URL: <a href="/{{ url_object.url_id }}" class="card-text" target="_blank">{{ site_url }}{{ url_object.url_id }}</a></p>
                        <p class="card-text">Original URL: <a href="{{ url_object.url }}" class="card-text" target="_blank">{{ url_object.url }}</a></p>
                        <p class="card-text">Created on: {{ url_object.date_created }}</p>
                        <p class="card-text">Days to expiration: {{ url_object.days_to_expiry }}</p>
                    </div>
                </div>
                {% endif %}
                </div>
            </div>
        </div>
        <div class="col-sm-2"></div>
    </div>
</div>

{% comment %}
    <form method="post">
        {% csrf_token %}
        <label for="url">Url: </label>
        <input type="text" id="url" name="url">
        <label for="days" >Days: </label>
        <input type="text" name="days" id="days">
        <input type="submit" value="Submit">
    </form>
    <p>Results:</p>
    {% if url_object %}
        {{ url_object.url_id }}
        {{ url_object.url }}
        {{ url_object.date_created }}
        {{ url_object.days_to_expiry }}
    {% endif %}
{% endcomment %}
{% endblock %}

templates/shortener/user_urls.html
{% extends 'shortener/base.html' %}
{% load custom_tags %}
{% block content %}
    <div class="container">
        {% for url in user_urls %}

            <div class="row mt-5">
                <div class="col-sm-2"></div>
                <div class="col-sm-8">
                    <div class="card text-center">
                        <div class="card-header">
                            {{ forloop.counter }}
                        </div>
                        <div class="card-body">
                            <p class="card-text">URL: <a href="/{{ url.url_id }}" class="card-text" target="_blank">{{ site_url }}{{ url.url_id }}</a></p>
                            <p class="card-text">Original URL: <a href="{{ url.url }}" class="card-text" target="_blank">{{ url.url }}</a></p>
                            <p class="card-text">Created on: {{ url.date_created }}</p>
                            <p class="card-text">Expiry date: {{ url.date_created|plus_days:url.days_to_expiry}}</p>
                        </div>
                    </div>
                </div>
                <div class="col-sm-2"></div>
            </div>
        {% endfor %}
    </div>
{% endblock %}